grocerly/core/urls.py
from django.urls import path
from . import views

app_name = 'core'

urlpatterns = [
    # Homepage
    path('', views.index, name='index'),
    path('products/', views.product_list_view, name='product-list'),
    path('products/<p_id>/', views.product_detail_view, name='product-detail'),

    # Category
    path('categories/', views.category_list_view, name='category-list'),
    path('categories/<c_id>/', views.category_product_list_view, name='category-product-list'),

    # Vendor
    path('vendors/', views.vendor_list_view, name='vendor-list'),
    path('vendors/<v_id>/', views.vendor_detail_view, name='vendor-detail'),

    # Tags
    path('products/tag/<slug:tag_slug>/', views.tag_list, name='tags'),

    # Add Review (AJAX)
    path('ajax-add-review/<int:p_id>/', views.ajax_add_review, name='ajax-add-review'),

    # Search
    path('search/', views.search_view, name='search'),

    # Cart
    path('add-to-cart/', views.add_to_cart, name='add-to-cart'),
    path('cart/', views.cart_view, name='cart'),
    path('delete-from-cart/', views.delete_item_from_cart, name='delete-from-cart'),
    path('update-cart/', views.update_cart, name='update-cart'),

    # Checkout + Payment
    path('save-checkout-info/', views.save_checkout_info, name='save_checkout_info'),
    path('api/create-checkout-session/<oid>/', views.create_checkout_session, name='api_checkout_session'),
    path('checkout/<oid>/', views.checkout, name='checkout'),
    path('payment-completed/<oid>/', views.payment_completed_view, name='payment-completed'),
    path('payment-failed/', views.payment_failed_view, name='payment-failed'),

    # Dashboard
    path('dashboard/', views.customer_dashboard, name='dashboard'),
    path('dashboard/order/<int:id>/', views.order_detail, name='order-detail'),

    # Address
    path('make-default-address/', views.make_address_default, name='make-default-address'),

    # Wishlist
    path('wishlist/', views.wishlist_view, name='wishlist'),
    path('add-to-wishlist/', views.add_to_wishlist, name='add-to-wishlist'),
    path('remove-from-wishlist/', views.remove_wishlist, name='remove-from-wishlist'),
]

grocerly/grocerly/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('user/', include('userauths.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

grocerly/core/forms.py
from django import forms
from core.models import ProductReview


class ProductReviewForm(forms.ModelForm):
    review = forms.CharField(widget=forms.Textarea(attrs={'placeholder': 'Write your review'}))

    class Meta:
        model = ProductReview
        fields = ['review', 'rating']

grocerly/core/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import JsonResponse
from django.db.models import Avg, Count
from django.db.models.functions import ExtractMonth
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.template.loader import render_to_string
from django.views.decorators.csrf import csrf_exempt
from django.urls import reverse
from django.conf import settings
from django.core import serializers
from taggit.models import Tag

import calendar
import stripe

from core.models import (
    Category, Vendor, Product, ProductReview, ProductImage,
    CartOrder, CartOrderItem, Wishlist, Address, Coupon,
)
from core.forms import ProductReviewForm
from userauths.models import Profile


# Create your views here.
def index(request):
    # products = Product.objects.all().order_by('-id')

    products = Product.objects.filter(featured=True, product_status='published').order_by('-id')

    context = {
        'products': products
    }

    return render(request, 'core/index.html', context)


def category_list_view(request):
    categories = Category.objects.all()

    context = {
        'categories': categories
    }

    return render(request, 'core/category-list.html', context)


def product_list_view(request):
    products = Product.objects.filter(product_status='published').order_by('-id')
    tags = Tag.objects.all().order_by('-id')[:6]

    context = {
        'products': products,
        'tags': tags,
    }

    return render(request, 'core/product-list.html', context)


def category_product_list_view(request, c_id):
    category = Category.objects.get(c_id=c_id)
    products = Product.objects.filter(category=category, product_status='published').order_by('-id')

    context = {
        'category': category,
        'products': products
    }

    return render(request, 'core/category-product-list.html', context)


def vendor_list_view(request):
    vendors = Vendor.objects.all()

    context = {
        'vendors': vendors
    }

    return render(request, 'core/vendor-list.html', context)


def vendor_detail_view(request, v_id):
    vendor = Vendor.objects.get(v_id=v_id)
    products = Product.objects.filter(vendor=vendor, product_status='published').order_by('-id')
    context = {
        'vendor': vendor,
        'products': products
    }

    return render(request, 'core/vendor-detail.html', context)


def product_detail_view(request, p_id):
    product = Product.objects.get(p_id=p_id)
    images = product.p_image.all()
    related_products = Product.objects.filter(category=product.category, product_status='published').exclude(p_id=p_id).order_by('-id')[:4]

    # Getting all reviews related to the product
    reviews = ProductReview.objects.filter(product=product).order_by('-date')

    # Getting average review rating
    average_rating = ProductReview.objects.filter(product=product).aggregate(rating=Avg('rating'))

    # Product Review form
    review_form = ProductReviewForm()

    make_review = True

    if request.user.is_authenticated:
        user_review_count = ProductReview.objects.filter(user=request.user, product=product).count()
        if user_review_count > 0:
            make_review = False

    context = {
        'p': product,
        'p_image': images,
        'related_products': related_products,
        'reviews': reviews,
        'average_rating': average_rating,
        'review_form': review_form,
        'make_review': make_review,
    }

    return render(request, 'core/product-detail.html', context)


def tag_list(request, tag_slug=None):
    products = Product.objects.filter(product_status='published').order_by('-id')

    tag = None
    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        products = products.filter(tags__in=[tag])

    context = {
        'products': products,
        'tag': tag,
    }

    return render(request, 'core/tag.html', context)


def ajax_add_review(request, p_id):
    product = Product.objects.get(pk=p_id)
    user = request.user

    review = ProductReview.objects.create(
        user=user,
        product=product,
        review=request.POST['review'],
        rating=request.POST['rating'],
    )

    context = {
        'user': user.username,
        'review': request.POST['review'],
        'rating': request.POST['rating'],
    }

    average_reviews = ProductReview.objects.filter(product=product).aggregate(rating=Avg('rating'))

    return JsonResponse({
        'bool': True,
        'context': context,
        'average_reviews': average_reviews,
    })


# ======================== Search ========================

def search_view(request):
    query = request.GET.get("q")
    products = Product.objects.filter(title__icontains=query, product_status='published').order_by('-date')

    context = {
        'products': products,
        'query': query,
    }
    return render(request, 'core/search.html', context)


# ======================== Cart (Session-based) ========================

def add_to_cart(request):
    cart_product = {}

    cart_product[str(request.GET['id'])] = {
        'title': request.GET['title'],
        'qty': request.GET['qty'],
        'price': request.GET['price'],
        'image': request.GET['image'],
        'pid': request.GET['pid'],
    }

    if 'cart_data_obj' in request.session:
        if str(request.GET['id']) in request.session['cart_data_obj']:
            cart_data = request.session['cart_data_obj']
            cart_data[str(request.GET['id'])]['qty'] = int(cart_product[str(request.GET['id'])]['qty'])
            cart_data.update(cart_data)
            request.session['cart_data_obj'] = cart_data
        else:
            cart_data = request.session['cart_data_obj']
            cart_data.update(cart_product)
            request.session['cart_data_obj'] = cart_data
    else:
        request.session['cart_data_obj'] = cart_product

    return JsonResponse({
        'data': request.session['cart_data_obj'],
        'totalcartitems': len(request.session['cart_data_obj']),
    })


def cart_view(request):
    cart_total_amount = 0
    if 'cart_data_obj' in request.session:
        for p_id, item in request.session['cart_data_obj'].items():
            cart_total_amount += int(item['qty']) * float(item['price'])
        return render(request, 'core/cart.html', {
            'cart_data': request.session['cart_data_obj'],
            'totalcartitems': len(request.session['cart_data_obj']),
            'cart_total_amount': cart_total_amount,
        })
    else:
        messages.warning(request, "Your cart is empty")
        return redirect("core:index")


def delete_item_from_cart(request):
    product_id = str(request.GET['id'])
    if 'cart_data_obj' in request.session:
        if product_id in request.session['cart_data_obj']:
            cart_data = request.session['cart_data_obj']
            del request.session['cart_data_obj'][product_id]
            request.session['cart_data_obj'] = cart_data

    cart_total_amount = 0
    if 'cart_data_obj' in request.session:
        for p_id, item in request.session['cart_data_obj'].items():
            cart_total_amount += int(item['qty']) * float(item['price'])

    context = render_to_string("core/async/cart-list.html", {
        'cart_data': request.session['cart_data_obj'],
        'totalcartitems': len(request.session['cart_data_obj']),
        'cart_total_amount': cart_total_amount,
    })
    return JsonResponse({
        'data': context,
        'totalcartitems': len(request.session['cart_data_obj']),
    })


def update_cart(request):
    product_id = str(request.GET['id'])
    product_qty = request.GET['qty']

    if 'cart_data_obj' in request.session:
        if product_id in request.session['cart_data_obj']:
            cart_data = request.session['cart_data_obj']
            cart_data[str(request.GET['id'])]['qty'] = product_qty
            request.session['cart_data_obj'] = cart_data

    cart_total_amount = 0
    if 'cart_data_obj' in request.session:
        for p_id, item in request.session['cart_data_obj'].items():
            cart_total_amount += int(item['qty']) * float(item['price'])

    context = render_to_string("core/async/cart-list.html", {
        'cart_data': request.session['cart_data_obj'],
        'totalcartitems': len(request.session['cart_data_obj']),
        'cart_total_amount': cart_total_amount,
    })
    return JsonResponse({
        'data': context,
        'totalcartitems': len(request.session['cart_data_obj']),
    })


# ======================== Checkout + Payment ========================

@login_required
def save_checkout_info(request):
    cart_total_amount = 0
    total_amount = 0

    if request.method == "POST":
        full_name = request.POST.get("full_name")
        email = request.POST.get("email")
        mobile = request.POST.get("mobile")
        address = request.POST.get("address")
        city = request.POST.get("city")
        state = request.POST.get("state")
        country = request.POST.get("country")

        if 'cart_data_obj' in request.session:
            for p_id, item in request.session['cart_data_obj'].items():
                total_amount += int(item['qty']) * float(item['price'])

            order = CartOrder.objects.create(
                user=request.user,
                price=total_amount,
                full_name=full_name,
                email=email,
                phone=mobile,
                address=address,
                city=city,
                state=state,
                country=country,
            )

            for p_id, item in request.session['cart_data_obj'].items():
                cart_total_amount += int(item['qty']) * float(item['price'])

                CartOrderItem.objects.create(
                    order=order,
                    invoice_no="INVOICE_NO-" + str(order.id),
                    item=item['title'],
                    image=item['image'],

grocerly/templates/core/async/cart-list.html
<main class="main" id="cart-list">
    <div class="page-header breadcrumb-wrap">
        <div class="container">
            <div class="breadcrumb">
                <a href="/" rel="nofollow"><i class="fi-rs-home mr-5"></i>Home</a>
                <span></span> Shop
                <span></span> Cart
            </div>
        </div>
    </div>
    <div class="container mb-80 mt-50">
        <div class="row">
            <div class="col-lg-8 mb-40">
                <h1 class="heading-2 mb-10">Your Cart</h1>
                <div class="d-flex justify-content-between">
                    <h6 class="text-body">There are <span class="text-brand">{{ totalcartitems }}</span> products in your cart</h6>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-8">
                <div class="table-responsive shopping-summery">
                    <table class="table table-wishlist">
                        <thead>
                            <tr class="main-heading">
                                <th scope="col">Product</th>
                                <th scope="col">Title</th>
                                <th scope="col">Unit Price</th>
                                <th scope="col" class="text-center">Quantity</th>
                                <th scope="col">Subtotal</th>
                                <th scope="col">Refresh</th>
                                <th scope="col" class="end">Remove</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for product_id, item in cart_data.items %}
                            <tr class="pt-30">
                                <td class="image product-thumbnail pt-40"><img src="{{ item.image }}" alt="#"></td>
                                <td class="product-des product-name">
                                    <h6 class="mb-5"><a class="product-name mb-10 text-heading" href="{% url 'core:product-detail' item.pid %}">{{ item.title }}</a></h6>
                                </td>
                                <td class="price" data-title="Price">
                                    <h4 class="text-body">${{ item.price|floatformat:2 }}</h4>
                                </td>
                                <td class="text-center detail-info" data-title="Stock">
                                    <div class="mr-15">
                                        <input type="number" placeholder="Qty" class="w-25 product-qty-{{ product_id }}" value="{{ item.qty }}" min="1">
                                    </div>
                                </td>
                                <td class="price" data-title="Price">
                                    <h4 class="text-brand">${% widthratio item.price 1 item.qty %}</h4>
                                </td>
                                <td class="action text-center" data-title="Refresh">
                                    <button style="border: none; background: none;" class="text-body update-product" data-product="{{ product_id }}"><i class="fi-rs-refresh"></i></button>
                                </td>
                                <td class="action text-center" data-title="Remove">
                                    <button style="border: none; background: none;" class="text-body delete-product" data-product="{{ product_id }}"><i class="fi-rs-trash"></i></button>
                                </td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
            <div class="col-lg-4">
                <div class="border p-md-4 cart-totals ml-30">
                    <div class="table-responsive">
                        <table class="table no-border">
                            <tbody>
                                <tr>
                                    <td class="cart_total_label"><h6 class="text-muted">Subtotal</h6></td>
                                    <td class="cart_total_amount"><h4 class="text-brand text-end">${{ cart_total_amount|floatformat:2 }}</h4></td>
                                </tr>
                                <tr>
                                    <td scope="col" colspan="2"><div class="divider-2 mt-10 mb-10"></div></td>
                                </tr>
                                <tr>
                                    <td class="cart_total_label"><h6 class="text-muted">Shipping</h6></td>
                                    <td class="cart_total_amount"><h5 class="text-heading text-end">Free</h5></td>
                                </tr>
                                <tr>
                                    <td class="cart_total_label"><h6 class="text-muted">Total</h6></td>
                                    <td class="cart_total_amount"><h4 class="text-brand text-end">${{ cart_total_amount|floatformat:2 }}</h4></td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                    {% if totalcartitems %}
                    <a href="{% url 'core:cart' %}" class="btn mb-20 w-100">Proceed To CheckOut<i class="fi-rs-sign-out ml-15"></i></a>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
</main>

grocerly/templates/core/async/wishlist-list.html
{% for item in w %}
<tr class="pt-30">
    <td class="custome-checkbox pl-30">
        <input class="form-check-input" type="checkbox" name="checkbox" id="exampleCheckbox{{ item.id }}" value="" />
        <label class="form-check-label" for="exampleCheckbox{{ item.id }}"></label>
    </td>
    <td class="image product-thumbnail pt-40"><img src="{{ item.product.image.url }}" alt="{{ item.product.title }}" /></td>
    <td class="product-des product-name">
        <h6><a class="product-name mb-10" href="{% url 'core:product-detail' item.product.p_id %}">{{ item.product.title|truncatechars:30 }}</a></h6>
    </td>
    <td class="price" data-title="Price">
        <span class="text-brand">$</span><span class="text-brand">{{ item.product.price }}</span>
    </td>
    <td class="text-center detail-info" data-title="Stock">
        <span class="stock-status in-stock mb-0">In Stock</span>
    </td>
    <td class="text-right" data-title="Cart">
        <input type="hidden" value="1" class="product-quantity-{{ item.product.id }}">
        <input type="hidden" class="product-pid-{{ item.product.id }}" value="{{ item.product.p_id }}">
        <input type="hidden" class="product-image-{{ item.product.id }}" value="{{ item.product.image.url }}">
        <input type="hidden" class="product-id-{{ item.product.id }}" value="{{ item.product.id }}">
        <input type="hidden" class="product-title-{{ item.product.id }}" value="{{ item.product.title }}">
        <button class="btn btn-sm add-to-cart-btn" data-index="{{ item.product.id }}">Add to cart</button>
    </td>
    <td class="action text-center" data-title="Remove">
        <button style="border: none; background: none;" data-wishlist-product="{{ item.id }}" class="text-body delete-wishlist-product"><i class="fi-rs-trash"></i></button>
    </td>
</tr>
{% empty %}
<tr>
    <td colspan="7"><p>Nothing in wishlist yet...</p></td>
</tr>
{% endfor %}